config/routes.rb
CpcadvApp::Application.routes.draw do

  get "admin/credits_withdraw/list" => "credits_withdraw#list"

  get "visitor_tracker/track"

  resources :payment_notifications

  get "share_offer/CreateLink"
  get "admin/offers" => "offers#index"
  get "/offers/new" =>"offers#new"
  post "/offers/create" =>"offers#create"
  get "/offers/promoteOffers" =>"offers#promoteAndSortOffers"
  get "/promoteOffers" =>"offers#promoteAndSortOffers"
  
  get "offers/:id/edit" => "offers#edit"
  
 put "offers/:id/edit" => "offers#update"
 
 post "/admin/offers/:id" => "offers#approverejectoffer"
 
 post "/admin/reoffers/:id" => "offers#reapproveoffer"
 

  get "admin/members" => "members#index"
  post "/members" => "members#create"
  post "/test" => "members#test"

  get "admin/dashboard" => "AdminUser#index"
  get "admin/members" => "members#index"
  
  post "/admin/members/:id" => "members#banuser"

  get "admin/categories" => "categories#index"
  get "admin/categories/new" => "categories#new"
  
  get "admin/categories/:id/edit" => "categories#edit"
  put "admin/categories/:id/edit" => "categories#update"
  delete "admin/categories/:id" => "categories#destroy"
  
  post "admin/categories/new" => "categories#create"
  
  put "admin/categories/new" => "categories#update"
  

  post "topup" => "offers#topup"

  post "login" => "home#login"

  post "updateMemberDetail" =>"members#updateMemberDetail"
  post "updateMemberSettings" =>"members#updateMemberSettings"

  get "sign_up" => "members#new", :as => "sign_up"
  get 'sortMyOffers/:qs/:sort_by/' =>'offers#sortMyOffers'

  get "/:member_random_code/:random_code" =>"visitor_tracker#track"
  get "mailverify" => "Members#mailverify"

  post "members/:id" => "Members#banuser"

  post "offers/:id" => "Offers#approverejectoffer"

  post "credits_withdraw/:id" => "credits_withdraw#updateCreditStatus"

  post "offers/os/:id" => "Offers#stopoffer"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'myOffers', to: 'offers#myOffers', as: 'myOffers'
  match 'mySettings', to: 'members#mySettings', as: 'mySettings'
  match 'withDrawCash', to: 'members#withDrawCash', as: 'withDrawCash'
  
  match 'sortOffers/:sort_by', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'sortOffers/:sort_by/:category_id', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'offerPayment/:offer_id', to: 'offers#offerPayment', as: 'offerPayment'
 
  match 'login', to: 'home#loginPage', as: 'login'

  root :to => 'home#index'

  get "admin" => "AdminUser#login"
  post  "admin" => "AdminUser#login"

  get "admin/log_out" => "AdminUser#logout"#, :as => "log_out"

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  
  layout  false
  
  include ApplicationHelper

   
   before_filter :user_is_logged_in, :except => [:index, :approverejectoffer]
   before_filter :redirect_to_other, :only => :index
  
  def index       
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    #abort("afad:#{session[:user_id]}")
    offerCheck = Offer.find(:all, 
                           :conditions => ["id = ? and member_id = ?", params[:id], session[:user_id]])    
    if offerCheck.count > 0 
       @offer = Offer.find(params[:id])
       return  
    else
      redirect_to root_url     
    end  
    
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])
    respond_to do |format|
    
    if @offer.save        
        insert_id = @offer.id
        random_string = SecureRandom.hex(5)
        Offer.find(insert_id).update_attribute(:random_code, random_string)
              
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
       #  redirect_to :action=>'promoteOffers?qs=myoffer' 
         redirect_to :controller => 'offers', :action => 'promoteAndSortOffers',  :qs => 'myoffer'
       # match 'promoteOffers', to: 'offers#promoteAndSortOffers', as: 'promoteOffers'
         return
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        if @offer.offer_status
           @offer.update_attribute(:offer_edit_reapprove, true)
        end       
        @offer.update_attribute(:offer_status, false)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        
         redirect_to :action=>'myOffers' 
         return
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
  
  def approverejectoffer
    @offer1 = Offer.find(params[:id])      
     if @offer1.offer_status
       
       if @offer1.offer_edit_reapprove
        @offer1.update_attribute(:offer_edit_reapprove , "false")
       end
       @offer1.update_attribute(:offer_status , "false")
       flash[:notice] = "You have successfully rejected offer"
     else
       @offer1.update_attribute(:offer_status , "true")
       flash[:notice] = "You have successfully approved offer"
     end        
    redirect_to :controller=>'offers', :action => 'index'    
    #flash[:notice] = ""     
  end
  
  def reapproveoffer    
    @offer1 = Offer.find(params[:id])  
     
      @offer1.update_attribute(:offer_edit_reapprove, false)
      @offer1.update_attribute(:offer_status, true)
            
        flash[:notice] = "You have successfully reapproved offer"
     

    redirect_to :controller=>'offers', :action => 'index'    
  end
  
  
  
  def stopoffer    
     @offer1 = Offer.find(params[:id])       
     if @offer1.offer_stop == false
       @offer1.update_attribute(:offer_stop , "true")
       flash[:offer_stop_notice] = "You have successfully stoped the offer"   
       redirect_url = "http://#{request.host}:#{request.port.to_s}/promoteOffers?qs=myoffer"
       
       redirect_to redirect_url          
       return                      
     end    
  end
  
  
  #method created by emamul khan
  def myOffers
    @logged_user_id = session[:user_id]
    objOff = Offer.new
    @offers = objOff.listMyOffers(session[:user_id], params[:page])
    #logger.debug "OFFER-LIST: #{@offers}"
  end
  
  
  def sortMyOffers
  #  logger.debug "check session #{session[:user_id]}"
   # abort("aborting khan")
    @logged_user_id = session[:user_id]
   # abort('adfa')
    #if !@logged_user_id
     # redirect_to root_url
      #return
    #end
           
   
    if session[:user_id]
      objMember = Member.new
      member_details = objMember.getMemberDataById(session[:user_id])
      arrParams = {
        :page_no      => params[:page],
        :member_id    => session[:user_id],
        :country_id   => member_details.country_id,
        :category_id  => params[:category_id],
        :sort_by      => params[:sort_by],
      }
      
      objOff = Offer.new
      @offers = objOff.sortMyOffers(arrParams)
    end
    render 'offers/promoteAndSortOffers'
  end
  
  
  
  def promoteAndSortOffers
  
   
    @logged_user_id = session[:user_id]
   
    if !@logged_user_id
      redirect_to root_url
      return
    end
           
    if params[:sort_by]
      @sort_by = params[:sort_by]
    else
      @sort_by = 'all'
    end
    if session[:user_id]
      objMember = Member.new
      member_details = objMember.getMemberDataById(session[:user_id])
      arrParams = {
        :page_no      => params[:page],
        :member_id    => session[:user_id],
        :country_id   => member_details.country_id,
        :category_id  => params[:category_id],
        :sort_by      => @sort_by,
        :qs        => params[:qs]
      }
      
      objOff = Offer.new
      @offers = objOff.getOffersToPromoteAndSort(arrParams)
    end
    logger.debug "urlparam: #{params[:qs]}"
  end 
  
  
  def offerPayment
    Offer.new.paypal_url(root_url, params[:offer_id])
  end
  
  
  def shareOffer
    
  end
  
 
     
  def topup   
     #encrypted = Offer.new.paypal_encrypted(params[:return_url],payment_notifications_url(:secret => APP_CONFIG[:paypal_secret]),params[:offer_id],true,params[:amount])
     notify_url = payment_notifications_url(:user_action => "topup") 
     redirect_to URI.encode("https://www.sandbox.paypal.com/cgi-bin/webscr" + "?cmd=_xclick&business=#{APP_CONFIG[:paypal_email]}&currency_code=USD&item_name=#{params[:offer_name]}&amount=#{params[:amount]}&invoice=#{params[:offer_id]}&rm=#{params[:rm]}&return=#{params[:return_url]}&quantity=1&notify_url=#{notify_url}")     
     return
  end
  
  

  
  
  
  end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
 <% if params[:id] %>
 <%= form_for(@offer,:url => url_for(:controller => 'offers', :action => 'update'), :html => { :multipart => true }) do |f| %>
 

  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :offer_name %><br />
    <%= f.text_field :offer_name %>
  </div>
  
  <% if params[:id]%>
  <div class="field">
  	<%= f.label :current_image %><br />
  	<%= image_tag @offer.image.url(:small) %>
  </div>
  
  <% end %>



  
  <div class="field">
  	<%= f.label :select_image %><br />
  	<%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :offer_link %><br />
    <%= f.text_field :offer_link %>
  </div>
  <div class="field">
    <%= f.label :offer_description %><br />
    <%= f.text_area :offer_description %>
  </div>
  <div class="field">
    <%= f.label :offer_msg %><br />
    <%= f.text_area :offer_msg %>
  </div>
  
  <%
  	if @offer.payment_status
  		disable_status = true
  	else
  		disable_status = false	
  	end	
  %>
  <div class="field">
    <%= f.label :offer_budget %><br />
    <%= f.number_field :offer_budget ,:disabled => disable_status %>
  </div>
  <div class="field">
    <%= f.label :offer_cr_per_click %><br />
    <%= f.number_field :offer_cr_per_click %>
  </div>
  <div class="field">
    <%= f.label :offer_max_clicks_per_user %><br />
    <%= f.number_field :offer_max_clicks_per_user %>
  </div>
  <div class="field">
    <%= f.label :offer_start_date %><br />          
    <%= f.text_field :offer_start_date, :readonly => 'true'%>
  </div>
  <div class="field">
    <%= f.label :offer_end_date %><br />
    <%= f.text_field :offer_end_date,:readonly => 'true' %>
  </div>
  <div class="field">
    <%= f.label :offer_worldwide %><br />
    <%= f.check_box :offer_worldwide %>
  </div>
    <%= f.hidden_field :member_id, :value => session[:user_id]  %>
    	    
    
  <div class="field">
  	
  	<%= f.label :category %><br />
  	<%=select("offer", "category_id", Category.all.collect {|ca| [ ca.category_name, ca.id ] }, {:prompt => 'Select Category'}) %>
  	
  </div>
  <div class="field" id="field_country">
    <%= f.label :country %><br />
    
    <%=select("offer", "country_id", Country.all.collect {|c| [ c.country, c.id ] }, {:prompt => 'Select Country'}) %>
    
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
 <% else %>
 
 <%= form_for(@offer,:url => url_for(:controller => 'offers', :action => 'create'), :html => { :multipart => true }) do |f| %>
 


  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :offer_name %><br />
    <%= f.text_field :offer_name %>
  </div>
  
  <% if params[:id]%>
  <div class="field">
  	<%= f.label :current_image %><br />
  	<%= image_tag @offer.image.url(:small) %>
  </div>
  
  <% end %>



  
  <div class="field">
  	<%= f.label :select_image %><br />
  	<%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :offer_link %><br />
    <%= f.text_field :offer_link %>
  </div>
  <div class="field">
    <%= f.label :offer_description %><br />
    <%= f.text_area :offer_description %>
  </div>
  <div class="field">
    <%= f.label :offer_msg %><br />
    <%= f.text_area :offer_msg %>
  </div>
  
  <%
  	if @offer.payment_status
  		disable_status = true
  	else
  		disable_status = false	
  	end	
  %>
  <div class="field">
    <%= f.label :offer_budget %><br />
    <%= f.number_field :offer_budget ,:disabled => disable_status %>
  </div>
  <div class="field">
    <%= f.label :offer_cr_per_click %><br />
    <%= f.number_field :offer_cr_per_click %>
  </div>
  <div class="field">
    <%= f.label :offer_max_clicks_per_user %><br />
    <%= f.number_field :offer_max_clicks_per_user %>
  </div>
  <div class="field">
    <%= f.label :offer_start_date %><br />          
    <%= f.text_field :offer_start_date, :readonly => 'true'%>
  </div>
  <div class="field">
    <%= f.label :offer_end_date %><br />
    <%= f.text_field :offer_end_date,:readonly => 'true' %>
  </div>
  <div class="field">
    <%= f.label :offer_worldwide %><br />
    <%= f.check_box :offer_worldwide %>
  </div>
    <%= f.hidden_field :member_id, :value => session[:user_id]  %>
    	    
    
  <div class="field">
  	
  	<%= f.label :category %><br />
  	<%=select("offer", "category_id", Category.all.collect {|ca| [ ca.category_name, ca.id ] }, {:prompt => 'Select Category'}) %>
  	
  </div>
  <div class="field" id="field_country">
    <%= f.label :country %><br />
    
    <%=select("offer", "country_id", Country.all.collect {|c| [ c.country, c.id ] }, {:prompt => 'Select Country'}) %>
    
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 <% end %>

app/views/offers/_myOfferLhs.html.erb
<div class="lhscontainer">
    <div class="lhs">    
		<h6>Sort Offers</h6>
        <ul>
        	<li>
        		<%=	link_to "Current Live Offers", :controller =>"offers", :action => "sortMyOffers", :qs => 'myoffer', :sort_by => "current_live",  %>
	        </li>
	        <li>
	        	<%=	link_to "Offers Awaiting Approval", :controller =>"offers", :action => "sortMyOffers", :qs => 'myoffer', :sort_by => "awaiting" %>
	        </li>
	        <li>
	        	<%=	link_to "Expired Offers", :controller =>"offers", :action => "sortMyOffers", :qs => 'myoffer', :sort_by => "expired" %>
	        </li>
        </ul>               
    </div>
</div>

app/views/offers/_offersList.html.erb
<script type="text/javascript">
	function toggleShareLinkDiv(divId) {
		$('#'+divId).toggle('slow');
	}
</script>
<div class="mainfrmcontainer">
	<% if params[:qs] == 'myoffer' %>
		<%= render 'offers/myOfferLhs' %>
	<% else %>
		<%= render 'home/lhs' %>
	<% end %>
	
		<p id="notice"><% if flash[:offer_stop_notice] %> <%= flash[:offer_stop_notice] %> <% end %></p>
	<% if !@offers.empty? %>
		<% @offers.each_with_index do |offer, index| %>						
			<div class="rhs">				
			    <%= image_tag(offer.image.url(:small), alt: offer.offer_name, class: 'imgr') %>     
			    
			    <%= #offer.offer_status 
			    %>  
			    <%
			    	if offer.offer_status
				%>			    		
			    	  <h6><%= offer.offer_name %></h6>	
			    <%	  
			    	else
 				%>			    		
			    		  <h6><%= offer.offer_name %>&nbsp;(Awaiting Approval...)&nbsp;</h6>	
			   <%
			    	end					    	
			   %>
			  
			    <p><%= offer.offer_description %></p>
			
			    <p>
			    	<strong>CPC</strong> : 
			    	<%= offer.offer_cr_per_click %> 
			    	<strong> Max Credit</strong> : 
			    	<%= offer.offer_budget %>
			    	<strong>Country</strong> : 			    				    	
			    	<% if offer.offer_worldwide %>
			    		Worldwide
			    	<% else %>
			    		<%= Country.getcountryname(offer.country_id).country %>
			    	<% end %>
			    	
			    	
			    	
			    </p>
			    <p>
			    	<strong>Category</strong> : 
			    	<%= Category.getcategoryname(offer.category_id) %>			    
			    	<strong>Duration</strong> : 
			    	<%
			    		require 'date'
						start_date_format = format_date(offer.offer_start_date)
						start_date = DateTime.parse(start_date_format)
						
						end_date_format = format_date(offer.offer_end_date)
						end_date = DateTime.parse(end_date_format)
						
			    	%>		
			    
			    	    		
			    	<%
			    		if Date.today > end_date    	
			    			
			    	%>	
			    	testing
			    	<% end %>	    				    	
			    	<%=
						start_date.strftime("#{start_date.day.ordinalize} %b %Y")
			    	%>
			    	to
			    	<%=
						end_date.strftime("#{end_date.day.ordinalize} %b %Y")
			    	%>
			    	
			    
			    </p>
			    <% if @logged_user_id == offer.member_id %>
			    
			    	<% if offer.offer_status %>
			        <p>
			        	<% if offer.payment_status %>
			        		Payment of  $<%= offer.offer_budget * 120/100 %> USD has done.
			        	<% else	%>
			        		You have to pay : $<%= offer.offer_budget * 120/100 %> USD
			        	<% end %>			        				        				        	
			        </p>
			        <% end %>
				    <p>			    	
				    <%=	link_to "Edit", :controller =>"offers", :action => "edit", :id=>offer.id %>			  
				    </p>
				    <p>				    	
				    	<%=	link_to "View Analytics of Offer", 'javascript:void(0);', :onclick => "toggleShareLinkDiv('analytic_#{index}');" %> 
				    	<% if offer.payment_status  %>
				    	|
				    	<%=	link_to "Top Up Offer Budget", 'javascript:void(0);', :onclick => "toggleShareLinkDiv('topUp_#{index}');" %>
				    	<% end %>
				    	
				    	<% if offer.offer_status %>
				    		<% if offer.offer_stop %>
				    		<% else %>
				    			| <%= link_to 'Stop Offer', "offers/os/#{offer.id}", method: :stopoffer, data: { confirm: 'Are you sure want to stop this offer?' } %>				    	
				    		<% end  %>
				    	<% end %>	
				    	
				    	
				    	<% if offer.offer_status %>
				    		<% return_url = "https://#{request.host}#{request.fullpath}" %>
							<%= form_tag APP_CONFIG[:paypal_url] do %>  
								<%= hidden_field_tag :cmd, "_s-xclick" %>
								<%= hidden_field_tag :rurl, return_url %>
								
								<%= hidden_field_tag :encrypted, Offer.new.paypal_encrypted(return_url,payment_notifications_url(:secret => APP_CONFIG[:paypal_secret]), offer.id,false,0) %>
								<% if offer.payment_status == false	%>
								<p><%= submit_tag "Pay for the offer" %></p>
								<% end %>
							<% end %>
						<% end %>
					
					<div id="analytic_<%= index %>" style="display: none">
						
						<p><strong>Time since offer was lived:</strong>														
						<% if offer.payment_status %>
						<%=	time_diff_format(offer.offer_live_date,Time.now)	%>	
						<%	else %>	
						Offer is not lived yet	
						<% end %>
						</p>
						<%					
						offerredeemList = OfferRedeem.find(:all, 
             										 :select => "DISTINCT ON (members_id,offers_id) *")
						%>
						<p><strong>Total number of times offer is promoted:</strong>
						<%= 	offerredeemList.count %>
						</p>
						<%											   
							
							offerredeemList1 = OfferRedeem.find(:all, 
      												:conditions => ["offers_id = #{offer.id}"])									
																
						%>
						<p>
							<strong>Total number of unique users clicked:</strong>
							<%= 	offerredeemList1.count %>							
						</p>												
						<%					
							visitorTrackerList = VisitorTracker.find(:all,
																	 :conditions => ["offers_id = #{offer.id}"])
						%>
						<p>
							<strong>Total number of clicks:</strong>
							<%= 	visitorTrackerList.count %>				
						</p>
					</div>																				
					<div id="topUp_<%= index %>" style="display: none">					
						<%= form_tag("/topup") do %>														
							<%= label_tag 'amount', 'Enter amount' %>
							<%= text_field_tag :amount, params[:amount] %>	
							<%  return_url = "https://#{request.host}#{request.fullpath}" %>
							
							<%= hidden_field_tag :return_url,return_url  %>
							<%= hidden_field_tag :rm,1  %>
							<%= hidden_field_tag :offer_id,offer.id  %>
							<%= hidden_field_tag :offer_name,offer.offer_name  %>							
							<p><%= submit_tag "Pay" %></p>
						<% end %>
					</div>				
				    </p>
				<% else %>
					<%= link_to "Share This Offer", 'javascript:void(0);', :onclick => "toggleShareLinkDiv('shareLink_#{index}');" %>
					<div id="shareLink_<%= index %>" style="display: none">												
						<% 
							current_url = "http://#{request.host}/"	
							random_code = offer.random_code		
							objMember = Member.new	
							member_random_code = objMember.getMemberDataById(@logged_user_id).random_code
												
							full_url = "#{current_url}#{member_random_code}/#{random_code}"							
						%>												
						<a href="<%= "#{full_url.strip}/" %>"><%= "#{full_url.strip}/" %></a>											
					</div>
			    <% end %>
			</div>
		<% end %>
		<%= paginate @offers %>
	<% else %>			
		<% if action_name == 'promoteAndSortOffers' && params[:qs] != 'myoffer' %>
			No Offers Found.
		<% elsif action_name == 'promoteAndSortOffers' && params[:qs] == 'myoffer'%>	
			You have not listed any offer yet, <%= link_to('click here', 'offers/new') %> to list an offer!
		<% else %>
			<% if params[:sort_by] == 'awaiting' %>
				No offers awaiting approval.
			<% elsif params[:sort_by] == 'current_live' %>
				No live offers are there.
			<% elsif params[:sort_by] == 'expired' %>
				No expired offers are there.
			<% end %>
			
		<% end %>
	<% end %>
</div>

app/views/offers/edit.html.erb
<%= render 'home/header' %>
<div class="mainfrmcontainer">
<h1>Editing offer</h1>
<%= render 'form' %>
</div>
<%= render 'home/footer' %>

app/views/offers/myOffers.html.erb
<%= render 'home/header' %>
<%= render 'offers/offersList' %>
<%= render 'home/footer' %>

app/views/offers/new.html.erb
<%= render 'home/header' %>
<div class="mainfrmcontainer">
<h1>New offer</h1>

<%= render 'form' %>


</div>
<%= render 'home/footer' %>

app/views/offers/promoteAndSortOffers.html.erb
<%= render 'home/header' %>
	<%= render 'offers/offersList' %>
<%= render 'home/footer' %>

app/views/offers/promoteOffers.html.erb
<%= render 'home/header' %>
<%= render 'offers/offersList' %>
<%= render 'home/footer' %>

app/views/offers/promoteOffers1.html.erb
<%= render 'home/header' %>

	asdasd
	<div id="time_div">
	</div>
   
	
	<%=  link_to "hello", :controller => "share_offer", :action => "CreateLink", "data-href" => "/share_offer/CreateLink", "data-type" => :json , :remote => true %>
	
    <span id="username_check">&nbsp;</span>  
<%= render 'home/footer' %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<!---
<p>
  <b>Offer name:</b>
  <%= @offer.offer_name %>
</p>

<p>
  <b>Offer link:</b>
  <%= @offer.offer_link %>
</p>

<p>
  <b>Offer description:</b>
  <%= @offer.offer_description %>
</p>

<p>
  <b>Offer msg:</b>
  <%= @offer.offer_msg %>
</p>

<p>
  <b>Offer budget:</b>
  <%= @offer.offer_budget %>
</p>

<p>
  <b>Offer cr per click:</b>
  <%= @offer.offer_cr_per_click %>
</p>

<p>
  <b>Offer max clicks per user:</b>
  <%= @offer.offer_max_clicks_per_user %>
</p>

<p>
  <b>Offer start date:</b>
  <%= @offer.offer_start_date %>
</p>

<p>
  <b>Offer end date:</b>
  <%= @offer.offer_end_date %>
</p>

<p>
  <b>Offer worldwide:</b>
  <%= @offer.offer_worldwide %>
</p>

<p>
  <b>Offer status:</b>
  <%= @offer.offer_status %>
</p>

<p>
  <b>Category:</b>
  <%= @offer.category %>
</p>

<p>
  <b>Country:</b>
  <%= @offer.country %>
</p>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>
--->