config/routes.rb
CpcadvApp::Application.routes.draw do

  get "admin/credits_withdraw/list" => "credits_withdraw#list"

  get "visitor_tracker/track"

  resources :payment_notifications

  get "share_offer/CreateLink"
  get "admin/offers" => "offers#index"
  get "/offers/new" =>"offers#new"
  post "/offers/create" =>"offers#create"
  get "/offers/promoteOffers" =>"offers#promoteAndSortOffers"
  get "/promoteOffers" =>"offers#promoteAndSortOffers"
  
  get "offers/:id/edit" => "offers#edit"
  
 put "offers/:id/edit" => "offers#update"
 
 post "/admin/offers/:id" => "offers#approverejectoffer"
 
 post "/admin/reoffers/:id" => "offers#reapproveoffer"
 

  get "admin/members" => "members#index"
  post "/members" => "members#create"
  post "/test" => "members#test"

  get "admin/dashboard" => "AdminUser#index"
  get "admin/members" => "members#index"
  
  post "/admin/members/:id" => "members#banuser"

  get "admin/categories" => "categories#index"
  get "admin/categories/new" => "categories#new"
  
  get "admin/categories/:id/edit" => "categories#edit"
  put "admin/categories/:id/edit" => "categories#update"
  delete "admin/categories/:id" => "categories#destroy"
  
  post "admin/categories/new" => "categories#create"
  
  put "admin/categories/new" => "categories#update"
  

  post "topup" => "offers#topup"

  post "login" => "home#login"

  post "updateMemberDetail" =>"members#updateMemberDetail"
  post "updateMemberSettings" =>"members#updateMemberSettings"

  get "sign_up" => "members#new", :as => "sign_up"
  get 'sortMyOffers/:qs/:sort_by/' =>'offers#sortMyOffers'

  get "/:member_random_code/:random_code" =>"visitor_tracker#track"
  get "mailverify" => "Members#mailverify"

  post "members/:id" => "Members#banuser"

  post "offers/:id" => "Offers#approverejectoffer"

  post "credits_withdraw/:id" => "credits_withdraw#updateCreditStatus"

  post "offers/os/:id" => "Offers#stopoffer"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'myOffers', to: 'offers#myOffers', as: 'myOffers'
  match 'mySettings', to: 'members#mySettings', as: 'mySettings'
  match 'withDrawCash', to: 'members#withDrawCash', as: 'withDrawCash'
  
  match 'sortOffers/:sort_by', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'sortOffers/:sort_by/:category_id', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'offerPayment/:offer_id', to: 'offers#offerPayment', as: 'offerPayment'
 
  match 'login', to: 'home#loginPage', as: 'login'

  root :to => 'home#index'

  get "admin" => "AdminUser#login"
  post  "admin" => "AdminUser#login"

  get "admin/log_out" => "AdminUser#logout"#, :as => "log_out"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_name, :status
  validates_uniqueness_of :category_name
  validates_presence_of :category_name
  
  
  def self.getcategoryname(category_id)
     category_name = Category.find(category_id).category_name
  end
  
  def getAllCategories
    categoryList = Category.find(:all)
    return categoryList
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
   layout false   
   include ApplicationHelper

   
   before_filter :redirect_to_other
    
  def index
    categories = Category.all
    @cat_results = Kaminari.paginate_array(categories).page(params[:page]).per(5)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

  
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    
      if @category.save              
         flash[:cat_create_success] = "Category was successfully created."                     
         redirect_to :controller=>'categories', :action => 'index'                     
      else
                 render "categories/new"      
      end
   
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    
      if @category.update_attributes(params[:category])                   
         # render "categories/edit"
          flash[:cat_update_success] = "Category was successfully updated."                     
          redirect_to :controller=>'categories', :action => 'index'

      else
          render "categories/edit"           
      end
   
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

     redirect_to :controller=>'categories', :action => 'index'  
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <% if params[:id] %>
 
  <%= form_for(@category,:url => url_for(:controller => 'categories', :action => 'update')) do |f| %>
  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="field">
   <%= f.label :status %><br />
   <%= f.radio_button :status, TRUE, :checked => true %>Active
   <%= f.radio_button :status, FALSE %>Inactive
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  
  
  <% else %>
  
  <%= form_for(@category,:url => url_for(:controller => 'categories', :action => 'new')) do |f| %>
  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="field">
   <%= f.label :status %><br />
   <%= f.radio_button :status, TRUE, :checked => true %>Active
   <%= f.radio_button :status, FALSE %>Inactive
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  
  
  
  <% end %>
  
  
  

app/views/categories/edit.html.erb
<%= render 'admin_user/admin_header' %>

<%= render 'admin_user/admin_lhs' %>

<div class="rhscontent">
<h1>Editing category</h1>


<% if @category.errors.any? %>
    <div class="error_messages">     
      <ul>
        <% for message in @category.errors.full_messages %>
          <li><%= message %></li> 
        <% end %>
      </ul>
    </div>
<% end %>




<%= render 'form' %>



</div>
</div>
<%= render 'admin_user/admin_footer' %>

app/views/categories/index.html.erb
<%= render 'admin_user/admin_header' %>

<%= render 'admin_user/admin_lhs' %>

<div class="rhscontent">
<% if @cat_results.count == 0 %>
<h1>There is no categories.</h1>
<% else %>


<h1>List of Categories</h1>
<table>
	<% if flash[:cat_create_success] %>
		<tr>
			<td colspan="5"><%= flash[:cat_create_success] %></td>
		<tr>
	<% end %>
	
	
	
	<% if flash[:cat_update_success] %>
		<tr>
			<td colspan="5"><%= flash[:cat_update_success] %></td>
		<tr>
	<% end %>
	
	
  <tr>
    <th>Category name</th>
    <th>Status</th>
    <th colspan="2">Action</th>
  </tr>

<% @cat_results.each do |category| %>
  <tr>
    <td><%= category.category_name %></td>
    <td>
    	
    	<% if category.status %>
    	 Active
    	<% else %>
    	 Inactive
    	<% end %>
    	
   </td>
 	<td >
			<%= link_to "Edit", :controller => "categories", :action => "update", :id => category.id %>
			<%= link_to 'Delete', "/admin/categories/#{category.id}", method: :delete, data: { confirm: 'Are you sure?' } %>
			
		</td>
    
  </tr>
<% end %>
<tr>
		

	</tr>
	<tr>
		<td colspan="3" align="right"><%= paginate @cat_results %></td>
	</tr>
</table>


<% end %>





<br />



 <%=  link_to "New Category", {:controller => "categories", :action => "new"} %>

</div>



</div>
<%= render 'admin_user/admin_footer' %>

app/views/categories/new.html.erb
<%= render 'admin_user/admin_header' %>

<%= render 'admin_user/admin_lhs' %>

<div class="rhscontent">

<h1>New category</h1>

<% if @category.errors.any? %>
    <div class="error_messages">     
      <ul>
        <% for message in @category.errors.full_messages %>
          <li><%= message %></li> 
        <% end %>
      </ul>
    </div>
<% end %>


<%= render 'form' %>
<%=  link_to "Back", {:controller => "categories", :action => "index"} %>

</div>



</div>
<%= render 'admin_user/admin_footer' %>

app/views/categories/show.html.erb
<%= render 'admin_user/admin_header' %>

<%= render 'admin_user/admin_lhs' %>

<div class="rhscontent">


<p id="notice"><%= notice %></p>

<p>
  <b>Category name:</b>
  <%= @category.category_name %>
</p>

<p>
  <b>Status:</b>
  
  <% if @category.status %>
    	 Active
  <% else %>
    	 Inactive
  <% end %>
    
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>


</div>



</div>
<%= render 'admin_user/admin_footer' %>