config/routes.rb
CpcadvApp::Application.routes.draw do

  get "admin/credits_withdraw/list" => "credits_withdraw#list"

  get "visitor_tracker/track"

  resources :payment_notifications

  get "share_offer/CreateLink"
  get "admin/offers" => "offers#index"
  get "/offers/new" =>"offers#new"
  post "/offers/create" =>"offers#create"
  get "/offers/promoteOffers" =>"offers#promoteAndSortOffers"
  get "/promoteOffers" =>"offers#promoteAndSortOffers"
  
  get "offers/:id/edit" => "offers#edit"
  
 put "offers/:id/edit" => "offers#update"
 
 post "/admin/offers/:id" => "offers#approverejectoffer"
 
 post "/admin/reoffers/:id" => "offers#reapproveoffer"
 

  get "admin/members" => "members#index"
  post "/members" => "members#create"
  post "/test" => "members#test"

  get "admin/dashboard" => "AdminUser#index"
  get "admin/members" => "members#index"
  
  post "/admin/members/:id" => "members#banuser"

  get "admin/categories" => "categories#index"
  get "admin/categories/new" => "categories#new"
  
  get "admin/categories/:id/edit" => "categories#edit"
  put "admin/categories/:id/edit" => "categories#update"
  delete "admin/categories/:id" => "categories#destroy"
  
  post "admin/categories/new" => "categories#create"
  
  put "admin/categories/new" => "categories#update"
  

  post "topup" => "offers#topup"

  post "login" => "home#login"

  post "updateMemberDetail" =>"members#updateMemberDetail"
  post "updateMemberSettings" =>"members#updateMemberSettings"

  get "sign_up" => "members#new", :as => "sign_up"
  get 'sortMyOffers/:qs/:sort_by/' =>'offers#sortMyOffers'

  get "/:member_random_code/:random_code" =>"visitor_tracker#track"
  get "mailverify" => "Members#mailverify"

  post "members/:id" => "Members#banuser"

  post "offers/:id" => "Offers#approverejectoffer"

  post "credits_withdraw/:id" => "credits_withdraw#updateCreditStatus"

  post "offers/os/:id" => "Offers#stopoffer"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'myOffers', to: 'offers#myOffers', as: 'myOffers'
  match 'mySettings', to: 'members#mySettings', as: 'mySettings'
  match 'withDrawCash', to: 'members#withDrawCash', as: 'withDrawCash'
  
  match 'sortOffers/:sort_by', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'sortOffers/:sort_by/:category_id', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'offerPayment/:offer_id', to: 'offers#offerPayment', as: 'offerPayment'
 
  match 'login', to: 'home#loginPage', as: 'login'

  root :to => 'home#index'

  get "admin" => "AdminUser#login"
  post  "admin" => "AdminUser#login"

  get "admin/log_out" => "AdminUser#logout"#, :as => "log_out"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome</title>


<%= stylesheet_link_tag    "admin_user", :media => "all" %>
<%= javascript_include_tag 'application' %>

<%= csrf_meta_tags %>






</head>

<body>
	<div id="wrapper">
    	<!--  Header start-->
    	<div id="header">
        	        	
        	 <%= image_tag("/assets/admin-images/logo.png", alt: "CPC logo", class: 'logo') %>
        	
        	
        	<% if session[:admin_user_id] %>
        	
            <div class="headerright">
            	<!--  Top serch sec start-->
            	<div class="tpsrc"></div>
                
            <!--  Top menu start-->
                <div class="tpmenu">                	                  
                  
					
						<%=  link_to "Home", {:controller => "AdminUser", :action => "index"}, :class => "active" %>
						
						<%=  link_to "Offers", {:controller => "offers", :action => "index"} %>
					
											
						<%= link_to "Users", :controller => "members", :action => "index"  %>
						<%= link_to "Categories", :controller => "categories", :action => "index"  %>
																			                                      				
                    
					<script>
                    gooeymenu.setup({id:'gooeymenu1', selectitem:0})
                    </script>                    
                </div>
                 <div class="tpmenu-rht"><strong>Welcome Admin!</strong><img src="images/user-icon.png" alt="" class="imgsz"/>
                    	<%= link_to "Log out", log_out_path %>
				</div>
            </div>
            <% end %>
            
            
            
            
        </div>
        <!--  Header End-->
        
        
        
        <div class="mainfrmcontainera">
		<% if session[:admin_user_id] %>
<div class="lhscontainer">
<div class="lhs">	
	<ul>
		<li>
		
			Total Number of Users: <%=  Member.all .size %>
		</li>
		<li>
			Total Number of Offers Promoted: <%=  Offer.all .size %>
		</li>
		<li>
			Total Number of Unique Clicks:
		</li>
		<li>
			Total Number of Clicks:
		</li>
		<li>
			Live Offers:
		</li>
		<li>
			Offers Awaiting Approval:
		</li>

	</ul>

</div>
</div>
<% end %>



<div class="rhscontent">


<%= yield %>

               
</div>



</div>


<div id="footer">
        	All Rights Reserved Copyright © 2012
            <div class="sntoolboxbt">
                <a title="Follow Us on Facebook" href="#" target="_blank">
                    <span class="facebook"></span>
                </a>
                <a title="Twitter" href="#" target="_blank">
                    <span class="twitter"></span>
                </a>

            </div>
        </div>

      
    </div>
</body>
</html>

        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cpc</title>
 <%= stylesheet_link_tag    "frontend", :media => "all" %>
 
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<!--  Header start-->
		<div id="header">
			
			<%= link_to image_tag("/assets/front-end-images/logo.png", alt: "CPC Advertising"), 'http://rubyonrails.org/' %>

			<div class="headerright">
				<!--  Top serch sec start-->
				<div class="tpsrc">
					<div id="user_nav">
						<%= notice %>
						
							<% if current_user %>
						    Signed in as <strong><%= current_user.username %></strong>!
						    <%= link_to "Sign out", signout_path, id: "sign_out" %>
						<% else %>
							
							<% if current_admin_user %>
							
							<% else %>
							
							<div class="srctxt">Already Member? <span>Login here:</span></div>
							<div class="tpfrmsec">
								<input name="" type="text" class="headtopinput" /> 
								<input name="" type="text" class="headtopinput" /> 
								<input name="" type="button" class="tplogin" value="Login" />
							</div>

							<% end %>						
						
						
							
						<% end %>
						
					</div>
				
				
					
				</div>
				
				<!--  Top menu start-->
				<div class="tpmenu">
					<a href="#" title="Home" class="active">Home</a>
						<a href="#" title="PROMOTE OFFERS">PROMOTE OFFERS</a>
						<%= link_to('LIST AN OFFER', 'offers/new', :title => 'LIST AN OFFER') %>
						<a href="#" title="YOUR OFFERS">YOUR OFFERS</a>
				</div>
			</div>
		</div>
		<!--  Header End-->
		
		
		<%= yield %>
		
		
		<!--  Footer Start-->
		<div id="footer">
			All Rights Reserved Copyright © 2012
			<div class="sntoolboxbt">
				<a title="Follow Us on Facebook" href="#" target="_blank">
					<span class="facebook"></span>
				</a>
				<a title="Twitter" href="#" target="_blank">
					<span class="twitter"></span>
				</a>

			</div>
		</div>
	</div>

</body>
</html>