config/routes.rb
CpcadvApp::Application.routes.draw do

  get "admin/credits_withdraw/list" => "credits_withdraw#list"

  get "visitor_tracker/track"

  resources :payment_notifications

  get "share_offer/CreateLink"
  get "admin/offers" => "offers#index"
  get "/offers/new" =>"offers#new"
  post "/offers/create" =>"offers#create"
  get "/offers/promoteOffers" =>"offers#promoteAndSortOffers"
  get "/promoteOffers" =>"offers#promoteAndSortOffers"
  
  get "offers/:id/edit" => "offers#edit"
  
 put "offers/:id/edit" => "offers#update"
 
 post "/admin/offers/:id" => "offers#approverejectoffer"
 
 post "/admin/reoffers/:id" => "offers#reapproveoffer"
 

  get "admin/members" => "members#index"
  post "/members" => "members#create"
  post "/test" => "members#test"

  get "admin/dashboard" => "AdminUser#index"
  get "admin/members" => "members#index"
  
  post "/admin/members/:id" => "members#banuser"

  get "admin/categories" => "categories#index"
  get "admin/categories/new" => "categories#new"
  
  get "admin/categories/:id/edit" => "categories#edit"
  put "admin/categories/:id/edit" => "categories#update"
  delete "admin/categories/:id" => "categories#destroy"
  
  post "admin/categories/new" => "categories#create"
  
  put "admin/categories/new" => "categories#update"
  

  post "topup" => "offers#topup"

  post "login" => "home#login"

  post "updateMemberDetail" =>"members#updateMemberDetail"
  post "updateMemberSettings" =>"members#updateMemberSettings"

  get "sign_up" => "members#new", :as => "sign_up"
  get 'sortMyOffers/:qs/:sort_by/' =>'offers#sortMyOffers'

  get "/:member_random_code/:random_code" =>"visitor_tracker#track"
  get "mailverify" => "Members#mailverify"

  post "members/:id" => "Members#banuser"

  post "offers/:id" => "Offers#approverejectoffer"

  post "credits_withdraw/:id" => "credits_withdraw#updateCreditStatus"

  post "offers/os/:id" => "Offers#stopoffer"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'myOffers', to: 'offers#myOffers', as: 'myOffers'
  match 'mySettings', to: 'members#mySettings', as: 'mySettings'
  match 'withDrawCash', to: 'members#withDrawCash', as: 'withDrawCash'
  
  match 'sortOffers/:sort_by', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'sortOffers/:sort_by/:category_id', to: 'offers#promoteAndSortOffers', as: 'sortOffers'
  match 'offerPayment/:offer_id', to: 'offers#offerPayment', as: 'offerPayment'
 
  match 'login', to: 'home#loginPage', as: 'login'

  root :to => 'home#index'

  get "admin" => "AdminUser#login"
  post  "admin" => "AdminUser#login"

  get "admin/log_out" => "AdminUser#logout"#, :as => "log_out"

end

app/models/member.rb
class Member < ActiveRecord::Base
  #attr_accessible :country_id, :email, :password, :provider, :status, :username
  
  attr_accessible :username, :password, :password_confirmation, :country_id, :provider, :status, :email, :age, :gender, :member_detail
  
  attr_accessor :password
  before_save :encrypt_password

  
  
  validates_uniqueness_of :username, :email
  
  
  validates_confirmation_of :password
  
  validates_presence_of :username, :email
  validates_format_of :email,
  :with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i  
  validates_presence_of :password, :password_confirmation, :gender, :age, :country_id
  validates_numericality_of :age, :only_integer => true, :message => "should be  whole number."
  
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  #method defined by emamul khan
  def self.saveMemberWhileLogin(auth)
    #logger.debug "MEMBER-TEST: #{auth["extra"]["raw_info"]["username"]}"
    #abort('khan')
    checkMember = self.find_by_email(auth["info"]["email"])
    #logger.debug "MEMBER-TEST-EMAIL: #{auth}"
    
    if checkMember
      if auth['provider'] = checkMember.provider
        return checkMember.id
      else
        return false
      end
    else
      objMember = Member.new
      objMember.username = auth["extra"]["raw_info"]["username"]
      objMember.email = auth["info"]["email"]
      objMember.password = 'CPC@ADV@APP'
      objMember.password_confirmation = 'CPC@ADV@APP'
      objMember.country_id = 'NULL'
      objMember.provider = auth["provider"]
      objMember.member_detail = "FALSE"
      objMember.gender = 'NULL'
      objMember.age = 0
      objMember.save!
      member_details = self.find_by_email(auth["info"]["email"])
      return member_details.id
    end
  end
  
  def self.authenticate_user(email, password)
      user = find_by_email(email)         
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
  end
  
  def getMemberDataById(member_id)
    member_data = Member.find(member_id)
    if member_data
      return member_data
    else
      return false
    end
  end
  
  def getMemberDataByRandomCode(random_code)
    member_data = Member.find_by_random_code(random_code)
    if member_data
      return member_data
    else
      return false
    end
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json

  layout false
  def index

    #logger.debug "admin-user-id: #{session[:admin_user_id]}"

    if session[:admin_user_id]
      members = Member.all
      @member_page = Member.all
      @results = Kaminari.paginate_array(members).page(params[:page]).per(5)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @members }
      end
    else
      redirect_to root_url
    return
    end
  end

  # GET /members/1
  # GET /members/1.json

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])     
    if @member.save
            
      require 'aweber'
      @oauth = AWeber::OAuth.new('Ak8Buwis5Q1j0OwvVZ4eJROe','TjtgHED5PIYPqS85ZgBekIf9jol1PgpUEpETmrV9')
      @oauth.authorize_with_access('Agvk8sGM8K4XFU2axg2d9z2j', 'qcAyJIPah2lBKcqrU85IviuOXjC0gLtYx0koG115')
      @aweber = AWeber::Base.new(@oauth)
      @account = @aweber.account

      new_subscriber = {}
      new_subscriber["email"] = params[:member][:email]
      new_subscriber["name"] = params[:member][:username]                            
      @account.lists.find_by_name("cpclist").subscribers.create(new_subscriber)
     
      
      insert_id = @member.id
      random_string = SecureRandom.hex(5)
      Member.find(insert_id).update_attribute(:random_code, random_string)

      flash[:success] = "Member was successfully created."
      session[:user_id] = insert_id
      redirect_to root_url
      #render   'home/index'

      flash[:success] = "";

    #render :partial => 'home/index', :locals => { :success => flash[:success] }
    else
      render   'home/index'
    end
  end

  # PUT /members/1
  # PUT /members/1.json

  # DELETE /members/1
  # DELETE /members/1.json

  def banuser
    if session[:admin_user_id]
      @member1 = Member.find(params[:id])
      if @member1.status
        @member1.update_attribute(:status , "false")
        flash[:notice] = "You have successfully banned user"
      else
        @member1.update_attribute(:status , "true")
        flash[:notice] = "You have successfully permited user"
      end
      redirect_to '/admin/members'
    else
      redirect_to root_url
    return
    end
  end

  def updateMemberDetail
    objMember = Member.new
    member_data = objMember.getMemberDataById(session[:user_id])
    #logger.debug "MEMBER-UPDATE-TEST: #{params[:gender]}"
    member_data.username = member_data.username
    member_data.email = member_data.email
    member_data.password = 'CPC@ADV@APP'
    member_data.password_confirmation = 'CPC@ADV@APP'
    member_data.gender = params[:gender]
    member_data.age = params[:age]
    member_data.country_id = params[:country_id]
    member_data.member_detail = true
    #if member_data.update_attributes :gender => params[:gender], :age => params[:age], :country_id => params[:country_id], :member_detail => true
    if member_data.save!
      flash[:member_detail_update_notice] = "Updated successfully."
    else
      flash[:member_detail_update_notice] = "Oops! Something went wrong."
    end
    #render   'members/MemberSetValues'
    redirect_to root_url
  end

  def mySettings
    logger.debug "current datetime: #{Time.now.strftime("%Y-%m-%d %H:%M:%S")}"

    objMember = Member.new
    @member_details = objMember.getMemberDataById(session[:user_id])
  end

  def updateMemberSettings
    objMember = Member.new
    member_data = objMember.getMemberDataById(session[:user_id])

    if params[:password].blank?
      flash[:member_setting_update_notice] = "Password can't be blank."
      redirect_to '/mySettings'
    return
    end

    if params[:password] ==  params[:password_confirmation]
      member_data.password = params[:password]
      member_data.password_confirmation =  params[:password_confirmation]
      member_data.country_id = params[:country_id]

      if member_data.save!
        flash[:member_setting_update_notice] = "Updated successfully."
      else
        flash[:member_setting_update_notice] = "Oops! Something went wrong."
      end
      redirect_to root_url
    else
      flash[:member_setting_update_notice] = "Password and confirmation password doesn't match"
      redirect_to '/mySettings'
    end

  end

  def withDrawCash

    if  @withDrawCash = CreditsWithdraw.find_by_members_id(session[:user_id])

      if @withDrawCash!= params[:email]
        random_string = SecureRandom.hex(16)

        if @withDrawCash.update_attributes(:paypal_email => params[:email], :email_verification => FALSE, :email_verification_code => random_string )

          url = "http://#{request.host}:#{request.port.to_s}/"

          UserMailer.paypal_email_verification(session[:user_id],url).deliver

          flash[:cw_update_notice] = "Email id has updated successfully."
        else
          flash[:cw_update_notice] = "Oops! Something went wrong."
        end
        redirect_to '/mySettings'
      end

    else
      objCw = CreditsWithdraw.new
      objCw.members_id = session[:user_id]
      objCw.paypal_email =  params[:email]
      objCw.credits = getcredit(session[:user_id])
      random_string = SecureRandom.hex(16)
      objCw.email_verification_code = random_string

      UserMailer.paypal_email_verification(session[:user_id],url).deliver

      if objCw.save!
        flash[:cw_update_notice] = "Email id has added to our database. Within few days you will get credit."
      else
        flash[:cw_update_notice] = "Oops! Something went wrong."
      end
      redirect_to '/mySettings'

    end

  end

  def mailverify

    user_id = params[:user_id]
    code = params[:code]

    if user_id.blank? || code.blank?
      redirect_to root_url
    return
    end

    @withDrawCash = CreditsWithdraw.find_by_members_id(user_id)

    if @withDrawCash.email_verification_code == code
      @withDrawCash.update_attribute(:email_verification,TRUE)
      render 'members/mailverify'
    else
      redirect_to root_url
    end

  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/MemberDashboard.html.erb
<%= render 'home/header' %>
	<div class="mainfrmcontainer">
	    <% if current_user %>
	        <%= render 'offers/offersList' %>
	    <% end %>
	</div>
<%= render 'home/footer' %>

app/views/members/MemberSetValues.html.erb
<%= render 'home/header' %>

<script type="text/javascript">
	/*if(window.opener) {
	   window.opener.location.reload(true);
	   window.close()
	}*/
</script>
  

<div class="mainfrmcontainer">
        <div class="rhs">
        	<% if  flash[:user_update_valuse_notice] %>
				<div class="error_messages" style="clear: left;">     
			      <ul>
			       <%=    flash[:user_update_valuse_notice] %>
			      </ul>
			    </div>
			<% end %>	
			<div style="float: left;">
			<%= form_tag("/updateMemberDetail", :method => "post") do  %>		   		
			 <p>
		      	<%= label_tag :gender %><br />
		       	<%= radio_button_tag :gender, 'm', :checked => true %>Male   
		       	<%= radio_button_tag :gender, 'f' %>Female             
      		</p>
			 <p>
		      	<%= label_tag :age %><br />
		      	<%= text_field_tag :age %>
      		</p>
      		<p>
      			<%= label_tag :country, "country" %><br />
      			<%= select_tag "country_id",   options_from_collection_for_select(Country.all.collect, "id", "country") , {:prompt => 'Select Country'} %>
      		</p> 
			<p>							
		    <%= submit_tag "Update",  :class => 'tplogin' %>
		    </p>								
			<% end %>
			</div>
        </div>
	
</div>
<%= render 'home/footer' %>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br />
    <%= f.number_field :country_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/_member_detail_form.html.erb
<% if  flash[:user_update_valuse_notice] %>
	<div class="error_messages" style="clear: left;">     
       <%= flash[:member_detail_update_notice] %>
    </div>
<% end %>
<%= form_tag("members/updateMemberDetail", :method => "post") do  %>
  <p>
  	<%= label_tag :gender %><br />
  	<%= radio_button_tag :gender, 'm', :checked => true %>Male   
   	<%= radio_button_tag :gender, 'f' %>Female             
  </p>
  <p>
  	<%= label_tag :age %><br />
  	<%= text_field_tag :age %>
  </p>
  <p>
  	<%= label_tag :country, "country" %><br />
    <%= select_tag "country_id",   options_from_collection_for_select(Country.all.collect, "id", "country") , {:prompt => 'Select Country'} %>
	<%= submit_tag "Update",  :class => 'tplogin' %>
  </p>
<% end %>

app/views/members/_new.html.erb
<% if @member.errors.any? %>
    <div class="error_messages">     
      <ul>
        <% for message in @member.errors.full_messages %>
          <li><%= message %></li> 
        <% end %>
      </ul>
    </div>
<% end %>

<% if  flash[:success] %>
<div style="float:left; clear:left">
<p id="notice"><%=  flash[:success] %></p>
</div>
<% end %>

<%= form_for (@member) do |f| %>
	  <p>
      <%= f.label :username %><br />
      <%= f.text_field :username %>
      </p>
    
      <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
      </p>
      
      <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
      </p>

	  <p>
      	<%= f.label :password_confirmation, "Confirmation" %><br />
      	<%= f.password_field :password_confirmation %>
      </p>

	  <p>
      <%= f.label :gender %><br />
      
       <%= f.radio_button :gender, 'm', :checked => true %>Male   
       <%= f.radio_button :gender, 'f' %>Female             
      </p>
      
      <p>
      <%= f.label :age %><br />
      <%= f.text_field :age %>
      </p>
      
     
      
      <p>
      <%= f.label :country, "country" %><br />
      <%=select("member", "country_id", Country.all.collect {|c| [ c.country, c.id ] }, {:prompt => 'Select Country'}) %>
      </p> 
           
		<%= f.hidden_field :provider, :value => "CPC" %>

	<p>
      <%= f.submit "Sign Up!" %>
    </p>
      
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<%= render 'admin_user/admin_header' %>

<%= render 'admin_user/admin_lhs' %>

<div class="rhscontent">


<p id="notice"><%= notice %></p>

	<% if @results.count == 0 %>	
		<h1>There is no users.</h1>	
	<% else %>
		<h1>List of users</h1>
		<table>
  <tr>
    <th>Username</th>
    <th>Email</th>   
    <th>Country</th>
    <th>Account Type</th>
    <th>Status</th>
    <th>Action</th>
  </tr>

<% @results.each do |mem| %>
  <tr>
    <td><%= mem.username %></td>
    <td><%= mem.email %></td>    
    <%
    	 if mem.country_id != 0
    %>
    <td><%=   Country.getcountryname(mem.country_id).country %></td>
    <%
    	else
    %>
    	Offer Worldwide		
    <%
    	end
    %>
    <td>
    	
    	<% if mem.provider = 'CPC' %>
    		Normal
    	<% else %>
    		 	<%= mem.provider %>
    	<% end %>    	    	
    </td>
    <td>
    	<% if mem.status %>
    	 Active
    	<% else %>
    	 Inactive
    	<% end %>        	    
    </td>
    <td>
    	    <% if mem.status%>
    	  		<%= link_to 'Ban User', "/admin/members/#{mem.id}", method: :banuser, data: { confirm: 'Are you sure want to ban this user?' } %>
    	  	<% else %>
    	  	   	<%= link_to 'Permit User', "/admin/members/#{mem.id}", method: :banuser, data: { confirm: 'Are you sure want to permit this user?' } %>
    	  	<% end %>    	      	  	    	      	 
    </td>
   
  </tr>
<% end %>
	<tr>
		<td colspan="6"> </td>
	</tr>
	<tr>
		<td colspan="6" align="right">			
			<%	#logger.debug "paginate: #{paginate @results}"
				
			%>
			<%= paginate @results, :params => {:controller => 'members', :action => 'index'} %>
		</td>
	</tr>
</table>
	
		
	<% end %>






</div>



</div>
<%= render 'admin_user/admin_footer' %>

app/views/members/mailverify.html.erb
<%= render 'home/header' %>
	<div class="mainfrmcontainer">	
		<div class="rhs">
			Thank you for verifing your paypal mail.			
		</div>
	</div>
<%= render 'home/footer' %>

app/views/members/mySettings.html.erb
<script type="text/javascript">
	function toggleShareLinkDiv(divId) {
		$('#'+divId).toggle('slow');
	}
</script>
<%= render 'home/header' %>
	<div class="mainfrmcontainer">
		<%= render 'home/lhs' %>
		<div class="rhs">
        	<% if  flash[:member_setting_update_notice] %>
			    <%= flash[:member_setting_update_notice] %>
			<% end %>	
			
			
			
			<div style="float: left;">
				<%= form_tag("/updateMemberSettings", :method => "post") do  %>		
				
				<%
				
					objMember = Member.new
    				member_data = objMember.getMemberDataById(session[:user_id])  
					
					if member_data.provider =="CPC"
				
				%>
					<p>
				      	<%= label_tag :Password %><br />
				       	<%= password_field_tag :password %>
		      		</p>
					<p>
				      	<%= label :password_confirmation, "Confirm Password" %><br />
      					<%= password_field_tag :password_confirmation %>
		      		</p>
				<%
					end
				%>				   
		      		<p>
		      			<%= label_tag :country, "Country" %><br />
		      			<%= select_tag "country_id", options_from_collection_for_select(Country.all.collect, "id", "country", @member_details.country_id) , {:prompt => 'Select Country'} %>
		      		</p> 
					<p>							
				    <%= submit_tag "Update",  :class => 'tplogin' %>
				    </p>								
				<% end %>
					<br />
					<% if  flash[:cw_update_notice] %>
			    		<%= flash[:cw_update_notice] %>
					<% end %>	
					<%
						credits = getcredit(session[:user_id]) 
						
						if credits >= 1500
					%>
								
						Credits: <%= credits %>
						<br/>					
						<%
							@withdrawcredits = CreditsWithdraw.find_by_members_id(session[:user_id])		
							if @withdrawcredits.email_verification == FALSE
						%>		
								Your email <%= @withdrawcredits.paypal_email %> is not verified yet. Please verify your email to get credits.								
						<%
							else
						%>		
								Your email <%= @withdrawcredits.paypal_email %> is  verified.
						<%	end					
						%>	
						
						<%= tag "input", { "type" => "button", "value" => "WithDraw Credits to Cash", "onclick" => "toggleShareLinkDiv('withdrawCash')" } %>
					
						<div id="withdrawCash" style="display: none">						
							<%= form_tag("/withDrawCash", :method => "post") do  %>							
								<%= label_tag 'email', 'Enter paypal email:' %>
								<%= text_field_tag :email, params[:email] %>						
								<%= submit_tag "Submit",  :class => 'tplogin' %>					
							<% end %>
				   		</div>
						
					<% end %>
					
					
			</div>
        </div>
	</div>
<%= render 'home/footer' %>

app/views/members/new.html.erb
<h1>Sign Up</h1>

<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @member.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @member.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>




<%= form_for(@member) do |f| %>

	  <p>
      <%= f.label :username %><br />
      <%= f.text_field :username %>
      </p>
    
      <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
      </p>

	  <p>
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
      </p>
      
       <p>
      <%= f.label :country, "country" %><br />
      <%=select("member", "country_id", Country.all.collect {|c| [ c.country, c.id ] }, {:prompt => 'Select Country'}) %>
      </p> 
           
		<%= f.hidden_field :provider, :value => "CPC" %>

		
      <%= f.submit "Sign Up!" %>
      
<% end %>

<%= form_tag('http://www.google.com') %>
<%= f.submit "Sign Up!" %>
<% end %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>